sriProject: main.cpp Dumper.cpp Interface.cpp KnowledgeBase.cpp Parser.cpp QueryOperations.cpp RuleBase.cpp Query.cpp
	g++ -o sriProject  -std=c++0x \
	main.cpp				\
	Dumper.cpp					\
	Interface.cpp				\
	KnowledgeBase.cpp			\
	Parser.cpp					\
	QueryOperations.cpp 		\
	RuleBase.cpp				\
	Query.cpp
	
debug: main.cpp Dumper.cpp Interface.cpp KnowledgeBase.cpp Parser.cpp QueryOperations.cpp RuleBase.cpp Query.cpp
	g++ -g- o debug -std=c++11 main.cpp Dumper.cpp Interface.cpp KnowledgeBase.cpp Parser.cpp QueryOperations.cpp RuleBase.cpp Query.cpp 
