sriProject: main.cpp Dumper.cpp Interface.cpp KnowledgeBase.cpp Parser.cpp QueryOperations.cpp RuleBase.cpp Query.cpp ORThread.cpp Thread.cpp ANDThreadL.cpp ANDThreadR.cpp
	g++ -g -o sriProject -pthread  -std=c++0x \
	main.cpp					\
	Dumper.cpp					\
	Interface.cpp				\
	KnowledgeBase.cpp			\
	Parser.cpp					\
	QueryOperations.cpp 		\
	RuleBase.cpp				\
	Query.cpp					\
	ORThread.cpp				\
	Thread.cpp					\
	ANDThreadL.cpp				\
	ANDThreadR.cpp				\
	socket/TCPServerSocket.cpp	\
	socket/TCPSocket.cpp		
	

