sriProject: main.cpp Dumper.cpp Interface.cpp KnowledgeBase.cpp Parser.cpp QueryOperations.cpp RuleBase.cpp
	g++ main.cpp				\
	Dumper.cpp					\
	Interface.cpp				\
	KnowledgeBase.cpp			\
	Parser.cpp					\
	QueryOperations.cpp 		\
	RuleBase.cpp				\
	-o sriProject -std=c++11
debug: main.cpp Dumper.cpp Interface.cpp KnowledgeBase.cpp Parser.cpp QueryOperations.cpp RuleBase.cpp
	g++ -g main.cpp Dumper.cpp Interface.cpp KnowledgeBase.cpp Parser.cpp QueryOperations.cpp RuleBase.cpp -o debug -std=c++11
